copy /Y SipPlatform\*.h ..\..\MCU\trunk\cppsipstack\include
copy /Y SipParser\*.h ..\..\MCU\trunk\cppsipstack\include
copy /Y SdpParser\*.h ..\..\MCU\trunk\cppsipstack\include
copy /Y SipUserAgent\*.h ..\..\MCU\trunk\cppsipstack\include
copy /Y ServerPlatform\*.h ..\..\MCU\trunk\cppsipstack\include
copy /Y XmlParser\*.h ..\..\MCU\trunk\cppsipstack\include
copy /Y Debug\SipPlatform.lib ..\..\MCU\trunk\cppsipstack\lib32
copy /Y Debug\SipParser.lib ..\..\MCU\trunk\cppsipstack\lib32
copy /Y Debug\SdpParser.lib ..\..\MCU\trunk\cppsipstack\lib32
copy /Y Debug\SipUserAgent.lib ..\..\MCU\trunk\cppsipstack\lib32
copy /Y Debug\ServerPlatform.lib ..\..\MCU\trunk\cppsipstack\lib32
copy /Y Debug\XmlParser.lib ..\..\MCU\trunk\cppsipstack\lib32
