# Makefile for all of C++ SipStack3
#
# programmer : yee young han ( websearch@naver.com )
#            : http://blog.naver.com/websearch
# start date : 2020/11/03

all:
	cd ../SipPlatform && make
	cd ../SipParser && make
	cd ../SdpParser && make
	cd ../XmlParser && make
	cd SipStack3 && make
	cd SipUserAgent3 && make
	cd KSipServer3 && make
	cd SipSpeedLinux3 && make

clean:
	cd ../SipPlatform && make clean
	cd ../SipParser && make clean
	cd ../SdpParser && make clean
	cd ../XmlParser && make clean
	cd SipStack3 && make clean
	cd SipUserAgent3 && make clean
	cd KSipServer3 && make clean
	cd SipSpeedLinux3 && make clean

install:

