# Makefile for all of C++ SipStack2
#
# programmer : yee young han ( websearch@naver.com )
#            : http://blog.naver.com/websearch
# start date : 2020/10/30

all:
	cd ../SipPlatform && make
	cd SipParser2 && make
	cd SdpParser2 && make
	cd ../XmlParser && make
	cd SipStack2 && make
	cd SipUserAgent2 && make
	cd ServerPlatform2 && make
	cd KSipServer2 && make
	cd SipSpeedLinux2 && make
	cd TestSipParser2 && make
	cd TestSipUserAgent2 && make

clean:
	cd ../SipPlatform && make clean
	cd SipParser2 && make clean
	cd SdpParser2 && make clean
	cd ../XmlParser && make clean
	cd SipStack2 && make clean
	cd SipUserAgent2 && make clean
	cd ServerPlatform2 && make clean
	cd KSipServer2 && make clean
	cd SipSpeedLinux2 && make clean
	cd TestSipParser2 && make clean
	cd TestSipUserAgent2 && make clean

install:

